//! The `cr_*` consistency corpus, and the three findings it produced.
//!
//! `data/scenarios/cr_00 … cr_10` are generated by `tools/gen_regions.py` from
//! five conditions checked against the tape before a tick runs (A1 labour
//! balance, A2 goods balance, A3 money against Rule 3's bands, A4 genesis prices
//! against the technology's Leontief vector, A5 whether Rule 1 and Rule 3 can
//! both be satisfied by any stock level). The generator carries its own
//! falsification suite — `--selftest` shows each condition firing on a world
//! built to break it *and* staying silent on the other four. This file guards
//! the parts that only the engine can settle.
//!
//! **Every test here is paired with a control**, because each of the claims
//! below would pass on a broken engine if asserted alone:
//!
//! * "`cr_00` never moves" passes on an engine that does nothing. The control is
//!   `cr_00` displaced 10%, which must move violently.
//! * "the displaced world blows up" passes on an engine that blows up on
//!   everything. The control is `cr_00` itself, at 0 ulp.
//! * "`cr_01`'s channel is deadlocked" would be a fact about that tape. The
//!   control is the SAME tape with `s` raised, where the channel trades — one
//!   dial, and the verdict flips.
//!
//! # What these tests do NOT claim
//!
//! `cr_00` passing is a NECESSARY condition, not a sufficient one, and
//! `no_basin_of_attraction_only_a_dead_band` is the standing proof: the world
//! holds a price that is 5% WRONG just as happily as the right one, and reports
//! a full-PASS certificate for it. Nothing here is evidence that the mechanism
//! finds prices. See PLAN P4.7 RESULT 3.

use std::path::PathBuf;

use rustyecon::{
    kernel::AgentArm,
    scenario::loader,
    state::{GameData, SimState},
    systems::{clearing::PriceRule, run_tick},
    types::ids::{GoodId, MarketNodeId},
};

/// Long enough for a runaway to be unmistakable and short enough to keep the
/// suite quick. The certificates in `results/cr_*` are the 1,000-tick record;
/// this file is a regression guard, not a second scoring pass.
const TICKS: u64 = 200;

fn scenario_dir(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/scenarios").join(name)
}

struct Run {
    goods: Vec<String>,
    /// Posted price of every good at every node, per tick: `[tick][node][good]`.
    prices: Vec<Vec<Vec<f64>>>,
    /// `min(supply, demand)` per (node, good), per tick.
    cleared: Vec<Vec<Vec<f64>>>,
    /// Every inventory's holding of every good, per tick.
    inventory: Vec<Vec<Vec<f64>>>,
    scale: Vec<Vec<f64>>,
}

impl Run {
    fn good(&self, name: &str) -> GoodId {
        GoodId(self.goods.iter().position(|g| g == name)
            .unwrap_or_else(|| panic!("no good {name:?} in {:?}", self.goods)) as u32)
    }

    /// Worst ratio the good's price at node 0 ever reached against its genesis
    /// value, measured in log space so a halving and a doubling are the same
    /// size of move.
    fn worst_price_move(&self, good: GoodId) -> f64 {
        let first = self.prices[0][0][good.idx()];
        self.prices
            .iter()
            .map(|t| {
                let r = t[0][good.idx()] / first;
                if r >= 1.0 { r } else { 1.0 / r }
            })
            .fold(1.0_f64, f64::max)
    }

    fn total_cleared(&self, node: usize, good: GoodId) -> f64 {
        self.prices.iter().enumerate().map(|(i, _)| self.cleared[i][node][good.idx()]).sum()
    }
}

/// Run a tape, optionally after mutating its loaded data.
///
/// The mutations are applied to the loaded copy rather than to a second
/// directory on disk. That is deliberate and it is the point of the controls:
/// a second tape would be a second place for everything else to drift, and then
/// "one dial moved" would be an assertion instead of a fact.
fn run(name: &str, arm: AgentArm, mutate: impl FnOnce(&mut SimState, &mut GameData)) -> Run {
    let s = loader::load(&scenario_dir(name)).unwrap_or_else(|e| panic!("{name} loads: {e}"));
    let (mut state, mut gd, events) = (s.state, s.game_data, s.events);
    mutate(&mut state, &mut gd);
    let goods: Vec<String> = gd.goods.iter().map(|g| g.name.clone()).collect();
    let (nn, ng) = (gd.num_nodes(), gd.num_goods());

    let mut out = Run {
        goods,
        prices: Vec::with_capacity(TICKS as usize),
        cleared: Vec::with_capacity(TICKS as usize),
        inventory: Vec::with_capacity(TICKS as usize),
        scale: Vec::with_capacity(TICKS as usize),
    };
    for _ in 0..TICKS {
        run_tick(&mut state, &gd, &events, arm, PriceRule::Imbalance);
        out.prices.push((0..nn).map(|n| (0..ng)
            .map(|g| state.price(MarketNodeId(n as u32), GoodId(g as u32))).collect()).collect());
        out.cleared.push((0..nn).map(|n| (0..ng).map(|g| {
            let (node, good) = (MarketNodeId(n as u32), GoodId(g as u32));
            state.supply(node, good).min(state.demand(node, good))
        }).collect()).collect());
        out.inventory.push(state.inventories.iter()
            .map(|i| (0..ng).map(|g| i.get(GoodId(g as u32))).collect()).collect());
        out.scale.push(state.recipe_instances.iter().map(|ri| ri.chosen_size).collect());
    }
    out
}

fn plain(name: &str, arm: AgentArm) -> Run {
    run(name, arm, |_, _| {})
}

/// Scale one good's genesis price at every node, EMA included.
fn displace(good: &str, factor: f64) -> impl FnOnce(&mut SimState, &mut GameData) + '_ {
    move |state: &mut SimState, gd: &mut GameData| {
        let id = GoodId(gd.goods.iter().position(|g| g.name == good).expect("good") as u32);
        for n in 0..gd.num_nodes() {
            let node = MarketNodeId(n as u32);
            let p = state.price(node, id) * factor;
            state.set_price(node, id, p);
            state.set_price_ema(node, id, p);
        }
    }
}

// ── 1. The fixed point, and the control that stops it being vacuous ──────────

/// `cr_00` is a fixed point of the kernel's rules to 0 ulp — AND IT TRADES.
///
/// The volume half is not decoration. Every price staying put is also what a
/// dead economy looks like, and the corpus is full of those; PLAN's own
/// "a corpse prices well" caution is the standing reminder. So the assertion is
/// two-sided: nothing moved, and 32 hours of labour, 40 wheat, 40 flour and 12
/// services changed hands at Ashby on every one of the 200 ticks.
#[test]
fn cr_00_is_a_fixed_point_of_the_kernel_and_trades_at_full_volume() {
    let r = plain("cr_00", AgentArm::Kernel);
    for good in ["wheat", "flour", "labour", "services"] {
        let id = r.good(good);
        assert_eq!(r.worst_price_move(id), 1.0,
            "{good} moved: genesis {} -> worst {}", r.prices[0][0][id.idx()],
            r.prices.iter().map(|t| t[0][id.idx()]).fold(0.0_f64, f64::max));
    }
    // Scales, inventories and cleared volumes are all the tick-1 values, for
    // every tick, at every node — not just the prices.
    for t in 1..r.prices.len() {
        assert_eq!(r.scale[t], r.scale[0], "a desk changed scale at tick {t}");
        assert_eq!(r.inventory[t], r.inventory[0], "an inventory moved at tick {t}");
        assert_eq!(r.cleared[t], r.cleared[0], "clearing changed at tick {t}");
    }
    // Non-vacuous: these are the quantities gen_regions.py solved for.
    for (good, want) in [("labour", 32.0), ("wheat", 40.0), ("flour", 40.0), ("services", 12.0)] {
        assert_eq!(r.cleared[0][0][r.good(good).idx()], want,
            "{good} should clear {want} every tick at Ashby");
    }
}

/// THE CONTROL FOR THE TEST ABOVE. The same tape, one price scaled by 1.10, must
/// move violently — otherwise "nothing moved" was a statement about the harness.
///
/// 1.10 rather than 1.06 because the boundary is at ×1.051282 (see
/// `no_basin_of_attraction_only_a_dead_band`) and a control should not sit on a
/// knife edge it is not testing.
#[test]
fn a_displaced_cr_00_runs_away_which_is_what_makes_the_fixed_point_test_mean_anything() {
    let r = run("cr_00", AgentArm::Kernel, displace("flour", 1.10));
    let worst = ["wheat", "flour", "labour", "services"]
        .map(|g| r.worst_price_move(r.good(g)))
        .into_iter()
        .fold(1.0_f64, f64::max);
    assert!(worst > 100.0,
        "a 10% displacement should leave the dead band and run away; worst move was {worst}x");
}

// ── 2. No basin. A dead band. ────────────────────────────────────────────────

/// The finding that costs `cr_00`'s green certificate most of its weight.
///
/// Displaced inside `dead`, NOTHING happens — the wrong price is held exactly,
/// for ever, and the criteria call it stable. Displaced outside, everything
/// explodes. There is no displacement at which the price moves back.
///
/// The edge is arithmetic, not empirical: the mill's relative margin is
/// `(p_f − 0.5)/((p_f + 0.5)/2)`, which reaches `dead = 0.05` at
/// `p_f = 1.025/1.95`, i.e. ×1.0512820512820513. Derived first, bisected after.
/// The 1,000-tick certificates agree: ×1.0512 PASS, ×1.0514 FAIL.
#[test]
fn no_basin_of_attraction_only_a_dead_band() {
    const EDGE: f64 = 1.0512820512820513;

    for factor in [1.01, 1.02, 1.05] {
        let r = run("cr_00", AgentArm::Kernel, displace("flour", factor));
        let id = r.good("flour");
        assert_eq!(r.worst_price_move(id), 1.0,
            "inside the dead band the displaced price must not move at all (x{factor})");
        // And it does not move BACK either — that is the whole finding.
        let held = r.prices[r.prices.len() - 1][0][id.idx()];
        assert_eq!(held, 0.5 * factor,
            "x{factor}: the world settles on the WRONG price and holds it");
    }
    // Just inside and just outside the derived edge, on the same tape.
    let inside = run("cr_00", AgentArm::Kernel, displace("flour", EDGE - 1e-4));
    let outside = run("cr_00", AgentArm::Kernel, displace("flour", EDGE + 1e-4));
    assert_eq!(inside.worst_price_move(inside.good("flour")), 1.0,
        "just inside the derived edge the world must still be frozen");
    assert!(outside.worst_price_move(outside.good("flour")) > 2.0,
        "just outside the derived edge the world must leave; got {}",
        outside.worst_price_move(outside.good("flour")));
}

// ── 3. Rule 1 and Rule 3 contradict each other on a pass-through desk ────────

/// A channel operator posts above `b_out·flow` and buys below `s·flow`, so a
/// stock level doing both exists only where `b_out < s`. `cr_01` registers
/// `b_out = 2, s = 1`, and its wheat channel therefore buys NOTHING, ever.
///
/// ASSERTED AS A FAILURE rather than patched: the fix is a change to Rule 1 or
/// Rule 3 with its own derivation and its own A/B, and `cr_01` is left at `s = 1`
/// so this stays visible. See `a5_rule_window` in tools/gen_regions.py.
///
/// The control is in the same test and is what makes it a measurement: raising
/// `s` past `b_out` on the SAME loaded tape opens the window and the channel
/// trades. If the assertion held at every `s` it would be measuring the tape,
/// not the rule.
#[test]
fn a_channel_operator_deadlocks_whenever_b_out_exceeds_s() {
    let deadlocked = plain("cr_01", AgentArm::Kernel);
    let wheat = deadlocked.good("wheat");
    // Node 1 (Brindle) is where the haul BUYS. Nothing clears there at all: the
    // farm posts, and the only buyer never bids.
    assert_eq!(deadlocked.total_cleared(1, wheat), 0.0,
        "at s=1 < b_out=2 the wheat channel must never buy");

    // The control: one dial, on the same tape, in memory.
    for s in [3_u64, 4] {
        let open = run("cr_01", AgentArm::Kernel, |_, gd| gd.kernel.s = s);
        assert!(open.total_cleared(1, wheat) > 0.0,
            "at s={s} > b_out=2 the window is open and the channel must trade");
    }
    // And it is genuinely the inequality, not just "bigger s is better":
    // s = 2 sits exactly on b_out and the window is a single point.
    let edge = run("cr_01", AgentArm::Kernel, |_, gd| gd.kernel.s = 2);
    assert!(edge.total_cleared(1, wheat) < deadlocked.total_cleared(0, wheat),
        "at s == b_out the window is degenerate and trade is marginal");
}

// ── 4. The defect controls: one condition each, everything else identical ────

/// `cr_04` is `cr_00` with `participation` at 0.45 and NOTHING else changed —
/// the one defect this corpus isolates perfectly, because `participation` is the
/// only registered field that moves labour supply without moving consumption,
/// capacity, outlay or price.
///
/// Posted labour supply is `π·H`, which names no price, so `ε_s = 0` and no wage
/// clears the market. This is Phase 4's central finding reproduced on purpose in
/// a world that is otherwise exact — which is the strongest form the claim has
/// taken, since here there is nothing else to blame.
#[test]
fn breaking_only_the_labour_condition_is_enough_to_destroy_an_otherwise_exact_world() {
    let clean = plain("cr_00", AgentArm::Kernel);
    let broken = plain("cr_04", AgentArm::Kernel);
    assert_eq!(clean.worst_price_move(clean.good("flour")), 1.0);
    assert!(broken.worst_price_move(broken.good("flour")) > 10.0,
        "cr_04 should run away; worst flour move {}",
        broken.worst_price_move(broken.good("flour")));
    // And it is the labour market that cannot clear, not a general collapse:
    // supply is 0.45 of a demand that no price can reduce.
    let labour = broken.good("labour");
    assert!(broken.total_cleared(0, labour) < 0.5 * clean.total_cleared(0, clean.good("labour")),
        "cr_04's labour market must clear far less than cr_00's");
}

/// Money is exactly neutral on a solved tape.
///
/// `cr_03` is `cr_00` with every price and every currency balance doubled and
/// nothing else. Every REAL series must be bit-identical and every price exactly
/// 2×. This guards the GENERATOR as much as the engine: had any emitted number
/// been a currency amount that failed to scale — a floor, a reserve written as an
/// absolute, a price used where a ratio was meant — the two would diverge.
#[test]
fn cr_03_is_a_pure_redenomination_of_cr_00_to_zero_ulp() {
    let a = plain("cr_00", AgentArm::Kernel);
    let b = plain("cr_03", AgentArm::Kernel);
    let gbp = a.good("GBP");
    assert_eq!(a.scale, b.scale, "real capacity differs");
    for t in 0..a.prices.len() {
        for n in 0..a.prices[t].len() {
            for g in 0..a.prices[t][n].len() {
                let (pa, pb) = (a.prices[t][n][g], b.prices[t][n][g]);
                let want = if g == gbp.idx() { pa } else { 2.0 * pa };
                assert_eq!(pb, want, "price of good {g} at node {n}, tick {t}");
                assert_eq!(b.cleared[t][n][g], a.cleared[t][n][g],
                    "real cleared volume of good {g} differs at tick {t}");
            }
        }
        for (i, (ia, ib)) in a.inventory[t].iter().zip(&b.inventory[t]).enumerate() {
            for g in 0..ia.len() {
                let want = if g == gbp.idx() { 2.0 * ia[g] } else { ia[g] };
                assert_eq!(ib[g], want, "inventory {i}, good {g}, tick {t}");
            }
        }
    }
}

/// The legacy arm cannot hold `cr_00` — a world that is provably a fixed point
/// of the rules the kernel obeys.
///
/// Recorded as a test rather than a note because it is the sharpest available
/// separation of the two arms: the same tape, no displacement, and one arm sits
/// still while the other leaves. It is also the reason "consistency helps" must
/// be stated as "consistency helps the KERNEL": on the 1,000-tick certificates
/// legacy's median band over `cr_*` (3.96e5×) is WORSE than over `lr_*`
/// (1.52e5×), and it fails all three regions of `cr_00`.
#[test]
fn the_legacy_arm_cannot_hold_the_fixed_point_the_kernel_holds_exactly() {
    let legacy = plain("cr_00", AgentArm::Legacy);
    let worst = ["wheat", "flour", "labour", "services"]
        .map(|g| legacy.worst_price_move(legacy.good(g)))
        .into_iter()
        .fold(1.0_f64, f64::max);
    assert!(worst > 2.0, "legacy should leave the fixed point; worst move {worst}x");
}
